"use client";

// React Imports
import { FC, useMemo } from "react";

// TacoBI Imports
import { useTacoBI } from "../tacobi-config";

// Component Imports
import { KPICard } from "@/components/charts/KPICard";

export const KPICardsSection: FC = () => {
  // Fetch the dataset using TacoBI
  const { useDatasets } = useTacoBI();
  const [protocolStatsRequest] = useDatasets(["protocol-stats"]);

  // Split the data into multiple datasets
  const processedDatasets = useMemo(() => {
    if (protocolStatsRequest.state !== "loaded") return null;

    const sortedProtocolStats = protocolStatsRequest.source.sort(
      (a, b) =>
        new Date(a.block_time_day).getTime() -
        new Date(b.block_time_day).getTime(),
    );

    const datasets = {
      morphoTokensSupply: sortedProtocolStats.map((d): [string, number] => [
        d.block_time_day,
        d.MORPHO_tokens_supply,
      ]),
      vaultsRevenue: sortedProtocolStats.map((d): [string, number] => [
        d.block_time_day,
        d.vaults_revenue,
      ]),
    };

    return datasets;
  }, [protocolStatsRequest]);

  return (
    <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-2">
      <KPICard
        title="Curator Revenue"
        data={processedDatasets?.vaultsRevenue ?? null}
        description="The total amount of revenue generated by the vaults."
        datasetIds={["protocol-stats"]}
      />
      <KPICard
        title="Rewards"
        data={processedDatasets?.morphoTokensSupply ?? null}
        description="The total amount of rewards for suppliers and borrowers."
        datasetIds={["protocol-stats"]}
      />
    </div>
  );
};
