[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diskcache>=5.6.3",
    "fastapi[standard]>=0.115.12",
    "numpy>=2.2.4",
    "polars>=1.26.0",
]
