name: Publish Backend to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      
      - name: Build package
        run: uv build
          
      - name: Publish to PyPI
        run: uv publish
